# Generated by Django 5.1 on 2024-09-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_key_assignment', '0002_student_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
    ]
