# Generated by Django 5.1 on 2024-09-14 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_key_assignment', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
